### ISSUE TITLE
Stránka zapomenuté heslo

### ISSUE THREAD

**Issue by thiscodeworks** [HlidacStatu/Web#10]
Nadpisy se duplikují + jde odeslat zapomenuté heslo i na email který není registrován do systému.

<img width="1203" alt="screenshot 2018-11-04 at 19 48 13" src="https://user-images.githubusercontent.com/31419790/47968455-9540b080-e06a-11e8-8050-b188ca0970fb.png">

**Comment by michalblaha** [comment]
v dalsim releasu bude fixnuto
