### ISSUE TITLE
Špatná šířka odkazu "Jak vyhledávat"

### ISSUE THREAD

**Issue by thiscodeworks** [HlidacStatu/Web#11]
Má plnou šířku rodičovského bloku, jde tedy na něj kliknout ikdyž nejsi myší na textu.

<img width="890" alt="screenshot 2018-11-04 at 19 51 49" src="https://user-images.githubusercontent.com/31419790/47968504-34fe3e80-e06b-11e8-9818-544e671b3974.png">

**Comment by michalblaha** [comment]
fixnuto. pozor na cache css.
