### ISSUE TITLE
Prázdné query při vyhledávání

### ISSUE THREAD

**Issue by thiscodeworks** [HlidacStatu/Web#7]
Lze odeslat prázdné vyhledávání, poté zobrazí "Pro hledaný výraz Jakub Goldmann jsme bohužel nic nenašli"

**Comment by thiscodeworks** [comment]
Současně odkazy z "Nenašli co jste hledali" buď vedou na homepage nebo na 404

**Comment by michalblaha** [comment]
1) fixnuto v dalsim releaseu
2) fixne se samo pri release na ostrou verzi (relativni odkaz na stage nefunguje)
